apiVersion: v1
kind: Pod
metadata:
  labels:
    name: database-deploy
spec:
  containers:
    - name: dbconfig
      image: 709855634846.dkr.ecr.eu-west-1.amazonaws.com/dbconfig:LATEST
      command:
        - cat
      tty: true
