REVOKE CREATE, USAGE ON SCHEMA public FROM PUBLIC;

DROP USER if exists sars;
CREATE USER sars WITH
    PASSWORD '<rw-pwd>'
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT USAGE ON SCHEMA public TO sars;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sars;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO sars;


DROP USER if exists sars_ro;
CREATE USER sars_ro WITH
    PASSWORD '<ro-pwd>'
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT USAGE ON SCHEMA public TO sars_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO sars_ro;

--------------------------------------------------------------------------------------------

CREATE TABLE db_version AS
    SELECT '0.0' AS current_version, now() as updated;